language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token $firebase_token --non-interactive