language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $firebase_token
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master